### ISSUE TITLE
명령어 위키 작성

### ISSUE THREAD

**Issue by Pzsx** [Pzsx/mc.pzs.kr#1]
서버에서 쓰이고 있는 명령어를 위키에 작성합니다.

**Comment by Pzsx** [comment]
https://github.com/Pzsx/mc.pzs.kr/wiki/%EB%AA%85%EB%A0%B9%EC%96%B4

**Comment by Pzsx** [comment]
레비님이 일부 명령어 추가 함.
또 추가 될 경우 직접 여기에도 써주면 참 좋겠다..

**Comment by Pzsx** [comment]
현존하는 명령어가 모두 작성되면 이 이슈는 닫을거에요.

**Comment by DancingLittleBird** [comment]
다이아몬드 - 다야 등 같은 대상에 사용된 다른 표현 일원화.
어색한 문장 표현 일부 수정.
중복 표현 삭제 ("임의"의 좌표로 "랜덤" 텔레포트)
소제목 /home -> 홈 관련 명령어로 수정
명령어의 필수 인자와 선택 인자 일부 구분
실수로 내용이 이상해져서 복구...
